name = "GlobalGlacierAnalysis"
uuid = "d9107a52-f194-45c7-a473-1d13678f1fe6"
version = "0.0.2"
authors = ["Alex S. Gardner, JPL"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Aria2_jll = "9ab3bdc3-1250-5043-8fac-ac7e82d2cbc9"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BinStatistics = "41602cae-99cf-4169-ad6c-01f6ab844ef7"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
FastGeoProjections = "981663e8-0c94-46dd-b2cf-efc8480900ec"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FlexiJoins = "e37f2e79-19fa-4eb7-8510-b63b51fe0a37"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
GeoArrays = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoTiles = "2d466ccc-baa7-41f7-823f-6e09e7c71845"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GeometryOpsCore = "05efe853-fabf-41c8-927e-7063c8b9f013"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RangeExtractor = "0151565a-6c01-463c-b553-c2b2e3b729c0"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
SortTileRecursiveTree = "746ee33f-1797-42c2-866d-db2fce69d14d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Stencils = "264155e8-78a8-466a-aa59-c9b28c34d21a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ArchGDAL = "0.10"
Arrow = "2.8"
CairoMakie = "0.15"
Colors = "0.12"
DataFrames = "1.8"
DimensionalData = "0.29"
FastGeoProjections = "0.0.2"
GeoArrays = "0.9"
GeoInterface = "1.4"
GeoJSON = "0.8"
GeometryBasics = "0.5"
GeometryOps = "0.1"
GeometryOpsCore = "0.1"
ImageFiltering = "0.7"
Images = "0.26"
Interpolations = "0.15"
JLD2 = "0.5"
JSON = "1.4"
LibGEOS = "0.9"
LsqFit = "0.15"
MAT = "0.11"
Metaheuristics = "3.4"
NCDatasets = "0.14"
NearestNeighbors = "0.4"
ProgressMeter = "1.11"
RangeExtractor = "0.1"
Rasters = "0.14"
Shapefile = "0.13"
SortTileRecursiveTree = "0.1"
julia = "1.12"
